### ISSUE TITLE
Github broke extension again

### ISSUE THREAD

**Issue by alxhotel** [DennisSnijder/MakeGithubGreatAgain#61]
The black bar is back... Again...

**Comment by sepehr** [comment]
![FTS](https://i.giphy.com/2JiV5KBXRfdcI.gif)

**Comment by thieman** [comment]
![](http://4.bp.blogspot.com/-vLOAoksNY1Q/URFUvHAoV6I/AAAAAAAAJXE/ebJVVqBVqKE/s1600/not-like-this.gif)

**Comment by bntzio** [comment]
@alxhotel @sepehr @thieman I just released an up-to-date Chrome extension to get back the classic GitHub look, you can check out the repo [here](https://github.com/bntzio/github-classic) (feel free to submit pull requests)

The thing is, GitHub is constantly changing their CSS, and so the extensions break, last time that happened I submitted a PR to this repo to fix the issue but seems that Dennis is no longer active on this project, so I created my own extension in which I'll be updating it frequently since I hate the new
 black header look.

You can install it in the [Chrome Web Store](https://chrome.google.com/webstore/detail/github-classic/cjoajojnjmnefgkhnnpfjhmllgeeadjk?hl=en-US) guys 🙂

**Comment by sepehr** [comment]
Works like a charm! Thank you so much, @bntzio.
