### ISSUE TITLE
Add to addons.mozilla.org?

### ISSUE THREAD

**Issue by andymckay** [DennisSnijder/MakeGithubGreatAgain#9]
This extension works with absolutely zero changes in Firefox. Would be cool to make available to Firefox users too.

**Comment by DennisSnijder** [comment]
Thanks for suggestion this, I will take a look into this shortly.

**Comment by DennisSnijder** [comment]
@andymckay The firefox extension has been added to the GitHub repository.
The extension is in review @ addons.mozilla.org

**Comment by jay** [comment]
Is there a URL page for the addon extension, and FYI two things that hopefully won't threadjack this..

- @mdo has [indicated](https://twitter.com/mdo/status/830149416556191744) on twitter he plans to remove the class at some point.

- You may want to check out my [CSS](https://gist.github.com/jay/e99fe4fe7e7bd4feaf5f237e15717133) overriding Segoe UI with Arial, since last year Segoe is apparently the default for Windows user agents. 

A lot of changes are subject to the eye of the beholder. It's hard to please everyone, or almost everyone. I remember working on a frontend app where any time the UI would change some users would revolt. While I sympathize with the GitHub developers and frankly am not too bothered by this recent change it would be nice to have a theme choice built in to user accounts, like GitHub 2015, GitHub Early 2016, etc, to kind of take away some of the shock.

**Comment by DennisSnijder** [comment]
@jay We are aware of the Github changes and we are looking into solving this.

I just added the FireFox link to the README.MD file
https://addons.mozilla.org/firefox/addon/githubgreatagain/

Thanks for the suggestions 👍
